class PBViewUser():
    def __init__(self):
        self.activity = []
        self.addFriend = -1
        self.altar = None #PBViewUserAltar
        self.arena = None #PBViewArenaPVP
        self.arenaOpps = []
        self.army = None #PBViewArmy
        self.armyLayout = None #PlaybackData
        self.artifacts = []
        self.bagCapacity = -1
        self.blackList = []
        self.buildings = []
        self.buyRecord = []
        self.chartArtGid = []
        self.cityLevel = -1
        self.crusade = None #PBViewCrusade
        self.dailytasks = []
        self.enlargeProgress = -1
        self.equipFragments = []
        self.equips = []
        self.friendRelation = []
        self.friends = []
        self.gem = []
        self.gemFragment = []
        self.gemShop = None #PBViewUserGemShop
        self.giftReceiveNum = -1
        self.gifts = []
        self.gold = -1
        self.hasActivity = false
        self.hasArenaOpps = false
        self.hasArtifact = false
        self.hasArtifactFragment = false
        self.hasBlacks = false
        self.hasBuildings = false
        self.hasBuyRecord = false
        self.hasChartArtGid = false
        self.hasEquipFragment = false
        self.hasEquips = false
        self.hasFriends = false
        self.hasFriendsInvite = false
        self.hasGemFragment = false
        self.hasGems = false
        self.hasGift = false
        self.hasHelpUserInfo = false
        self.hasHeroes = false
        self.hasItems = false
        self.hasLayoutHero = false
        self.hasRelation = false
        self.hasScrolls = false
        self.hasSoulFragments = false
        self.hasTasks = false
        self.hasUserDailyTask = false
        self.helpUserInfo = None #PBViewHelpUserInfo
        self.heroArtFragments = []
        self.heroes = []
        self.instance = None #PBViewInstance
        self.inviteUsers = []
        self.items = []
        self.layoutHeros = []
        self.leftPowerRecoverTime = -1
        self.leftStaminaRecoverTime = -1
        self.level = -1
        self.mojo = -1
        self.monthCardDays = -1
        self.mysteryItem = None #PBViewUserMysteryItem
        self.power = -1
        self.raidInstance = None #PBViewRaidInstance
        self.scrolls = []
        self.soulFragments = []
        self.stamina = -1
        self.starChest = None #PBViewStarChest
        self.tasks = []
        self.tavern = None #PBViewUserTavern
        self.tech = None #PBViewUserTech
        self.usedPopulation = -1
        self.userGuide = None #PBViewUserGuide
        self.userInfo = None #PBViewUserSimple
        self.vip = None #PBViewUserVip
        self.wallHp = -1
        self.xp = -1
