# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import submodule.fanyoy.redis.static
import common.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EliteInstanceLevel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u540d\u79f0')),
                ('descriptionId', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u63cf\u8ff0')),
                ('instance_id', models.IntegerField(verbose_name='\u7bc7\u7ae0ID')),
                ('eliteMaxPlayCount', models.IntegerField(default=0, verbose_name='\u7cbe\u82f1\u6700\u5927\u6311\u6218\u6b21\u6570')),
                ('monsterId', models.IntegerField(default=0, verbose_name='BOSSid')),
                ('nameId', models.CharField(default=b'', max_length=30, verbose_name='\u540d\u5b57id')),
                ('scene', models.CharField(default=b'', max_length=60, verbose_name='\u573a\u666f\u540d\u5b57')),
                ('elitePowerCost', models.IntegerField(default=0, verbose_name='\u7cbe\u82f1\u6d88\u8017\u4f53\u529b')),
                ('levelIndex', models.IntegerField(default=0, verbose_name='\u5173\u5361\u4f4d\u7f6eindex')),
                ('eliteMinUserLevel', models.IntegerField(default=0, verbose_name='\u6700\u5c0f\u89e3\u9501\u7b49\u7ea7')),
                ('eliteHeroExp', models.IntegerField(default=0, verbose_name='\u82f1\u96c4\u7ecf\u9a8c')),
                ('eliteRevisionScale', models.FloatField(default=0, verbose_name='\u96be\u5ea6\u7cfb\u6570')),
                ('eliteNextInstanceId', models.IntegerField(default=0, verbose_name='\u4e0b\u4e00\u7cbe\u82f1\u5173\u5361\u7684id')),
                ('eliteGold', models.IntegerField(default=0, verbose_name='\u91d1\u94b1')),
                ('elitewoods_int', models.CharField(default=b'', max_length=100, verbose_name='\u7cbe\u82f1\u5404\u96be\u5ea6\u6389\u843d\u7684\u6728\u5934')),
                ('elitePlayerExp', models.IntegerField(default=0, verbose_name='\u7cbe\u82f1\u73a9\u5bb6\u7ecf\u9a8c')),
                ('eliteRewardId_int', models.CharField(default=b'', max_length=200, verbose_name='InstanceReward_int')),
                ('eliteProbability_float', models.CharField(default=b'', max_length=100, verbose_name='\u6389\u843d\u6982\u7387')),
                ('eliteCount_int', models.CharField(default=b'', max_length=100, verbose_name='\u5bf9\u5e94\u6570\u91cf')),
                ('mustEliteRewardId_int', models.CharField(default=b'', max_length=100, verbose_name='\u4e00\u5b9a\u6389\u843d\u7684id')),
                ('eliteEnemyIds_int', models.CharField(default=b'', max_length=500, verbose_name='\u7cbe\u82f1\u654c\u65b9\u9635\u5bb9')),
                ('zoneIDs_int', models.CharField(default=b'', max_length=1000, verbose_name='\u5173\u5361\u4f7f\u7528\u7684\u573a\u666f\u533a\u57df')),
                ('triggerInfos_int', models.CharField(default=b'', max_length=500, verbose_name='\u89e6\u53d1\u5668')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('warriorIds_int', models.CharField(default=b'', max_length=500, verbose_name='hero_gid_int')),
                ('posPoints_int', models.CharField(default=b'', max_length=500, verbose_name='\u7ad9\u4f4d')),
                ('propertyHeros_int', models.CharField(default=b'', max_length=200, verbose_name='\u7279\u5b9a\u5c5e\u6027\u52a0\u6210\u7684\u82f1\u96c4')),
                ('propertyIds_int', models.CharField(default=b'', max_length=200, verbose_name='\u7279\u5b9a\u5c5e\u6027ids')),
                ('skillIds_int', models.CharField(default=b'', max_length=200, verbose_name='\u589e\u52a0\u7684 \u6280\u80fdid-\u7b49\u7ea7')),
                ('propertyValues_float', models.CharField(default=b'', max_length=200, verbose_name='\u7279\u5b9a\u5c5e\u6027\u6570\u503c\u767e\u5206\u6bd4')),
                ('heroLevel', models.IntegerField(default=0, verbose_name='\u82f1\u96c4\u7b49\u7ea7')),
                ('heroStar', models.IntegerField(default=0, verbose_name='\u82f1\u96c4\u661f\u7ea7')),
                ('heroUp', models.IntegerField(default=0, verbose_name='\u82f1\u96c4\u52a0\u51e0')),
                ('soldierLevel', models.IntegerField(default=0, verbose_name='\u5c0f\u5175\u7b49\u7ea7')),
                ('skillLevel', models.IntegerField(default=0, verbose_name='\u6280\u80fd\u7b49\u7ea7')),
                ('equipLevel', models.IntegerField(default=0, verbose_name='\u88c5\u5907\u7b49\u7ea7')),
                ('equipUpgrade', models.IntegerField(default=0, verbose_name='\u88c5\u5907\u9636\u7ea7')),
                ('bubbleTypes_int', models.CharField(default=b'', max_length=500, verbose_name='\u6c14\u6ce1\u5206\u7c7b')),
                ('bubbleMessages_str', models.CharField(default=b'', max_length=500, verbose_name='\u6c14\u6ce1\u5185\u5bb9')),
                ('bubbleProperbility_float', models.CharField(default=b'', max_length=500, verbose_name='\u6c14\u6ce1\u51fa\u73b0\u6982\u7387')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='GuildInstanceLevel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u540d\u79f0')),
                ('descriptionId', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u63cf\u8ff0')),
                ('monsterId', models.IntegerField(default=0, verbose_name='BOSSid')),
                ('nameId', models.CharField(default=b'', max_length=30, verbose_name='\u540d\u5b57id')),
                ('scene', models.CharField(default=b'', max_length=60, verbose_name='\u573a\u666f\u540d\u5b57')),
                ('levelIndex', models.IntegerField(default=0, verbose_name='\u5173\u5361\u4f4d\u7f6eindex')),
                ('revisionScale_float', models.CharField(default=b'', max_length=100, verbose_name='revisionScale_float')),
                ('rewardId_int', models.CharField(default=b'', max_length=200, verbose_name='InstanceReward_int')),
                ('price_int', models.CharField(default=b'', max_length=200, verbose_name='\u4ef7\u683c')),
                ('probability_float', models.CharField(default=b'', max_length=100, verbose_name='\u6389\u843d\u6982\u7387')),
                ('count_int', models.CharField(default=b'', max_length=100, verbose_name='\u5bf9\u5e94\u6570\u91cf')),
                ('powerCost', models.IntegerField(default=0, verbose_name='\u6d88\u8017\u6d3b\u8dc3\u5ea6')),
                ('enemyIds_int', models.CharField(default=b'', max_length=100, verbose_name='\u654c\u4eba\u7684id')),
                ('zoneIDs_int', models.CharField(default=b'', max_length=1000, verbose_name='\u5173\u5361\u4f7f\u7528\u7684\u573a\u666f\u533a\u57df')),
                ('triggerInfos_int', models.CharField(default=b'', max_length=500, verbose_name='\u89e6\u53d1\u5668')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=200, verbose_name='\u7ae0\u8282\u540d\u79f0')),
                ('rewardIds_1_int', models.CharField(default=b'', max_length=200, verbose_name='Reward_int')),
                ('rewardCounts_1_int', models.CharField(default=b'', max_length=200, verbose_name='count_int')),
                ('rewardIds_2_int', models.CharField(default=b'', max_length=200, verbose_name='Reward_int')),
                ('rewardCounts_2_int', models.CharField(default=b'', max_length=200, verbose_name='count_int')),
                ('rewardIds_3_int', models.CharField(default=b'', max_length=200, verbose_name='Reward_int')),
                ('rewardCounts_3_int', models.CharField(default=b'', max_length=200, verbose_name='count_int')),
                ('eliteRewardIds_1_int', models.CharField(default=b'', max_length=200, verbose_name='Reward_int')),
                ('eliteRewardCounts_1_int', models.CharField(default=b'', max_length=200, verbose_name='count_int')),
                ('eliteRewardIds_2_int', models.CharField(default=b'', max_length=200, verbose_name='Reward_int')),
                ('eliteRewardCounts_2_int', models.CharField(default=b'', max_length=200, verbose_name='count_int')),
                ('eliteRewardIds_3_int', models.CharField(default=b'', max_length=200, verbose_name='Reward_int')),
                ('eliteRewardCounts_3_int', models.CharField(default=b'', max_length=200, verbose_name='count_int')),
                ('rewardsId_int', models.CharField(default=b'', max_length=500, verbose_name='\u5956\u52b1_int')),
                ('counts_int', models.CharField(default=b'', max_length=200, verbose_name='\u5956\u52b1_counts')),
                ('probability', models.FloatField(default=0, verbose_name='\u6982\u7387')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='InstanceLevel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u540d\u79f0')),
                ('descriptionId', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u63cf\u8ff0')),
                ('instance_id', models.IntegerField(verbose_name='\u7bc7\u7ae0ID')),
                ('maxPlayCount', models.IntegerField(default=0, verbose_name='\u6700\u5927\u6311\u6218\u6b21\u6570')),
                ('monsterId', models.IntegerField(default=0, verbose_name='BOSSid')),
                ('nameId', models.CharField(default=b'', max_length=30, verbose_name='\u540d\u5b57id')),
                ('playerExp', models.IntegerField(default=0, verbose_name='\u73a9\u5bb6\u7ecf\u9a8c')),
                ('scene', models.CharField(default=b'', max_length=60, verbose_name='\u573a\u666f\u540d\u5b57')),
                ('powerCost', models.IntegerField(default=0, verbose_name='\u6d88\u8017\u4f53\u529b')),
                ('levelIndex', models.IntegerField(default=0, verbose_name='\u5173\u5361\u4f4d\u7f6eindex')),
                ('minUserLevel', models.IntegerField(default=0, verbose_name='\u6700\u5c0f\u89e3\u9501\u7b49\u7ea7')),
                ('nextInstanceId', models.IntegerField(default=0, verbose_name='\u4e0b\u4e00\u5173\u5361id')),
                ('heroExp_int', models.CharField(default=b'', max_length=100, verbose_name='\u5404\u96be\u5ea6\u82f1\u96c4\u7ecf\u9a8c')),
                ('golds_int', models.CharField(default=b'', max_length=100, verbose_name='\u5404\u96be\u5ea6\u6389\u843d\u7684\u91d1\u94b1')),
                ('woods_int', models.CharField(default=b'', max_length=100, verbose_name='\u5404\u96be\u5ea6\u6389\u843d\u7684\u6728\u5934')),
                ('revisionScale_float', models.CharField(default=b'', max_length=100, verbose_name='revisionScale_float')),
                ('rewardId_int', models.CharField(default=b'', max_length=200, verbose_name='InstanceReward_int')),
                ('probability_float', models.CharField(default=b'', max_length=100, verbose_name='\u6389\u843d\u6982\u7387')),
                ('count_int', models.CharField(default=b'', max_length=100, verbose_name='\u5bf9\u5e94\u6570\u91cf')),
                ('mustRewardId_int', models.CharField(default=b'', max_length=100, verbose_name='\u4e00\u5b9a\u6389\u843d\u7684id')),
                ('enemyIds_int', models.CharField(default=b'', max_length=100, verbose_name='\u654c\u4eba\u7684id')),
                ('zoneIDs_int', models.CharField(default=b'', max_length=1000, verbose_name='\u5173\u5361\u4f7f\u7528\u7684\u573a\u666f\u533a\u57df')),
                ('triggerInfos_int', models.CharField(default=b'', max_length=500, verbose_name='\u89e6\u53d1\u5668')),
                ('instanceStartDialogID', models.IntegerField(default=0)),
                ('instanceEndDialogID', models.IntegerField(default=0)),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='InstanceReward',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descriptionId', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u63cf\u8ff0')),
                ('easyTextId', models.CharField(default=b'', max_length=200, verbose_name='id')),
                ('heroId', models.CharField(default=0, max_length=30, verbose_name='\u82f1\u96c4id')),
                ('nameId', models.CharField(default=b'', max_length=30, verbose_name='\u540d\u5b57id')),
                ('normalTextId', models.CharField(default=b'', max_length=30, verbose_name='\u6587\u5b57id')),
                ('openTimeTextId', models.CharField(default=b'', max_length=30, verbose_name='\u6587\u5b57id')),
                ('powerCost', models.IntegerField(default=0, verbose_name='\u4f53\u529b\u6d88\u8017')),
                ('textId', models.CharField(default=b'', max_length=30, verbose_name='\u6587\u5b57id')),
                ('category', models.IntegerField(default=0, verbose_name='\u7c7b\u578b')),
                ('raidLevelId_int', models.CharField(default=b'', max_length=200, verbose_name='\u6d3b\u52a8\u4e0b\u5305\u542b\u7684\u96be\u5ea6\u7b49\u7ea7')),
                ('vocationType', models.IntegerField(default=0, verbose_name='\u804c\u4e1a\u9650\u5236')),
                ('maxPlayCount', models.IntegerField(default=0, verbose_name='\u6700\u5927\u6311\u6218\u6b21\u6570')),
                ('experiment1', models.CharField(default=b'', max_length=200, verbose_name='\u5b9e\u9a8c1, \u5f00\u542f\u65e5\u671f')),
                ('experiment2', models.CharField(default=b'', max_length=200, verbose_name='\u5b9e\u9a8c2, \u53cc\u500d')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='RaidEnemyToReward',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('rewards_int', models.CharField(default=b'', max_length=200, verbose_name='\u5956\u52b1')),
                ('monsterId', models.IntegerField(default=0, verbose_name='\u602a\u7269\u6a21\u578b')),
                ('difficulty_int', models.CharField(default=b'', max_length=200, verbose_name='\u5956\u52b1')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='RaidInstanceCost',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('gold', models.IntegerField(default=0, verbose_name='\u6d88\u8017\u91d1\u94b1')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='RaidInstanceReward',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='RaidLevelBuff',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('iconId', models.CharField(max_length=100, verbose_name='\u56fe\u7247id')),
                ('mulLangId', models.CharField(max_length=100, verbose_name='\u591a\u8bed\u8a00id')),
                ('attribute', models.IntegerField(default=0, verbose_name='\u5c5e\u6027')),
                ('addition', models.FloatField(default=0.0, verbose_name='\u52a0\u6210')),
                ('starCost', models.IntegerField(default=0, verbose_name='\u82b1\u8d39')),
                ('star', models.IntegerField(default=0, verbose_name='\u54c1\u8d28')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='RaidLevelConf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nameId', models.CharField(default=b'', max_length=30, verbose_name='\u540d\u5b57id')),
                ('descriptionId', models.CharField(default=b'', max_length=200, verbose_name='\u5173\u5361\u63cf\u8ff0')),
                ('difficulty', models.IntegerField(default=0, verbose_name='\u96be\u5ea6')),
                ('heroExp', models.IntegerField(default=0, verbose_name='\u82f1\u96c4\u7ecf\u9a8c')),
                ('playerExp', models.IntegerField(default=0, verbose_name='\u73a9\u5bb6\u7ecf\u9a8c')),
                ('minUserLevel', models.IntegerField(default=0, verbose_name='\u6700\u5c0f\u89e3\u9501\u7b49\u7ea7')),
                ('maxUserLevel', models.IntegerField(default=0, verbose_name='\u6700\u5927\u89e3\u9501\u7b49\u7ea7')),
                ('monsterId', models.IntegerField(default=0, verbose_name='BOSSid')),
                ('revisionScale', models.FloatField(default=0, verbose_name='\u96be\u5ea6\u7cfb\u6570')),
                ('scene', models.CharField(default=b'', max_length=60, verbose_name='\u573a\u666f\u540d\u5b57')),
                ('gold', models.IntegerField(default=0, verbose_name='\u91d1\u5e01')),
                ('rewardId_int', models.CharField(default=b'', max_length=2500, verbose_name='InstanceReward_int')),
                ('probability_float', models.CharField(default=b'', max_length=700, verbose_name='\u6389\u843d\u6982\u7387')),
                ('count_int', models.CharField(default=b'', max_length=700, verbose_name='\u5bf9\u5e94\u6570\u91cf')),
                ('minCount_int', models.CharField(default=b'', max_length=700, verbose_name='\u5bf9\u5e94\u6ce2\u52a8\u6700\u5c0f\u6570\u91cf')),
                ('enemyIds_int', models.CharField(default=b'', max_length=1000, verbose_name='\u654c\u65b9\u9635\u5bb9')),
                ('iconId', models.CharField(default=b'', max_length=20, verbose_name='\u654c\u65b9\u9635\u5bb9')),
                ('raidLevelName', models.CharField(default=b'', max_length=100, verbose_name='\u5173\u5361\u540d\u5b57')),
                ('zoneIDs_int', models.CharField(default=b'', max_length=1000, verbose_name='\u5173\u5361\u4f7f\u7528\u7684\u573a\u666f\u533a\u57df')),
                ('triggerInfos_int', models.CharField(default=b'', max_length=500, verbose_name='\u89e6\u53d1\u5668')),
                ('backImageId', models.CharField(default=b'', max_length=20, verbose_name='\u80cc\u666fui\u56fe\u7247')),
                ('extroImageId', models.CharField(default=b'', max_length=20, verbose_name='\u989d\u5916\u65b0\u80cc\u666fui\u56fe\u7247')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='RaidLevelDifficulty',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('difficulty1', models.IntegerField(default=0, verbose_name='\u96be\u5ea61')),
                ('difficulty2', models.IntegerField(default=0, verbose_name='\u96be\u5ea62')),
                ('difficulty3', models.IntegerField(default=0, verbose_name='\u96be\u5ea63')),
                ('towerGold', models.IntegerField(default=0, verbose_name='\u722c\u5854\u5e01')),
                ('gold', models.IntegerField(default=0, verbose_name='\u91d1\u5e01')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='SmallGame',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('rewards_int', models.CharField(default=b'', max_length=100, verbose_name='smallintreward')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='SmallGameReward',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='SpaceTimeReward',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='SpaceTimeRewardDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('rewards_int', models.CharField(default=b'', max_length=200, verbose_name='\u901a\u5173\u5956\u52b1')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('triggerType', models.IntegerField(default=0, verbose_name='\u89e6\u53d1\u5668\u7c7b\u578b')),
                ('bOnce', models.IntegerField(default=0, verbose_name='bOnce')),
                ('data_int', models.CharField(default=b'', max_length=500, verbose_name='\u89e6\u53d1\u5668\u884c\u4e3a')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='TriggerData',
            fields=[
                ('id', models.BigIntegerField(serialize=False, verbose_name='\u4e3b\u952e', primary_key=True)),
                ('eventType', models.IntegerField(default=0, verbose_name='\u4e8b\u4ef6\u7c7b\u578b')),
                ('delay', models.FloatField(default=0.0, verbose_name='\u5ef6\u8fdf')),
                ('param_1', models.IntegerField(default=0, verbose_name='\u53c2\u65701')),
                ('param_2', models.IntegerField(default=0, verbose_name='\u53c2\u65702')),
                ('param_3', models.IntegerField(default=0, verbose_name='\u53c2\u65703')),
                ('param_4', models.IntegerField(default=0, verbose_name='\u53c2\u65704')),
                ('param_5', models.IntegerField(default=0, verbose_name='\u53c2\u65705')),
                ('param_6', models.IntegerField(default=0, verbose_name='\u53c2\u65706')),
                ('param_7', models.IntegerField(default=0, verbose_name='\u53c2\u65707')),
                ('param_8', models.IntegerField(default=0, verbose_name='\u53c2\u65708')),
                ('param_9', models.IntegerField(default=0, verbose_name='\u53c2\u65709')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='TriggerInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nameID', models.IntegerField(default=0, verbose_name='nameID')),
                ('triggerID', models.IntegerField(default=0, verbose_name='\u89e6\u53d1\u5668ID')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('attackDir', models.IntegerField(default=0, verbose_name='attackDir')),
                ('zoneID', models.IntegerField(default=0, verbose_name='\u533a\u57df\u7f16\u53f7')),
                ('startPoints_int', models.CharField(default=b'', max_length=200, verbose_name='startPoints')),
                ('airGatesToActivate_int', models.CharField(default=b'', max_length=200, verbose_name='airGatesToActivate')),
            ],
            bases=(models.Model, submodule.fanyoy.redis.static.StaticDataRedisHandler, common.models.CommonStaticModels),
        ),
    ]
