class PBViewCreate():
    def __init__(self):
        self.activity = []
        self.artfacts = []
        self.buildings = []
        self.buyRecords = []
        self.chartArtifactGid = []
        self.equipFragments = []
        self.equips = []
        self.fragments = []
        self.friendRelation = []
        self.friends = []
        self.gemFragment = []
        self.gems = []
        self.heroes = []
        self.instanceStar = []
        self.invites = []
        self.items = []
        self.scrolls = []
        self.soulFragments = []
        self.tasks = []
